import type { CppVersion, CppVersionId } from './types.js'

export const CPP_VERSIONS: Record<CppVersionId, CppVersion> = {
  cpp98: {
    id: 'cpp98',
    name: 'C++98',
    year: 1998,
    standardDoc: 'ISO/IEC 14882:1998',
    features: ['STL', 'Templates', 'Exceptions', 'RTTI'],
  },
  cpp03: {
    id: 'cpp03',
    name: 'C++03',
    year: 2003,
    standardDoc: 'ISO/IEC 14882:2003',
    features: ['Value initialization fix', 'Standard library fixes'],
  },
  cpp11: {
    id: 'cpp11',
    name: 'C++11',
    year: 2011,
    standardDoc: 'ISO/IEC 14882:2011',
    features: [
      'auto keyword',
      'Range-based for',
      'Lambda expressions',
      'Smart pointers',
      'Move semantics',
      'nullptr',
      'constexpr',
      'Variadic templates',
      'Thread support',
    ],
  },
  cpp14: {
    id: 'cpp14',
    name: 'C++14',
    year: 2014,
    standardDoc: 'ISO/IEC 14882:2014',
    features: [
      'Generic lambdas',
      'Return type deduction',
      'Variable templates',
      'Binary literals',
      'Digit separators',
      'std::make_unique',
    ],
  },
  cpp17: {
    id: 'cpp17',
    name: 'C++17',
    year: 2017,
    standardDoc: 'ISO/IEC 14882:2017',
    features: [
      'Structured bindings',
      'if constexpr',
      'Fold expressions',
      'std::optional',
      'std::variant',
      'std::string_view',
      'Filesystem library',
      'Parallel algorithms',
    ],
  },
  cpp20: {
    id: 'cpp20',
    name: 'C++20',
    year: 2020,
    standardDoc: 'ISO/IEC 14882:2020',
    features: [
      'Concepts',
      'Ranges',
      'Coroutines',
      'Modules',
      'Three-way comparison',
      'std::format',
      'std::span',
      'Calendar and timezone',
    ],
  },
  cpp23: {
    id: 'cpp23',
    name: 'C++23',
    year: 2023,
    standardDoc: 'ISO/IEC 14882:2023',
    features: [
      'std::expected',
      'std::flat_map',
      'std::mdspan',
      'std::generator',
      'Deducing this',
      'std::print',
      'Ranges improvements',
    ],
  },
  cpp26: {
    id: 'cpp26',
    name: 'C++26',
    year: 2026,
    standardDoc: 'ISO/IEC 14882:2026 (Draft)',
    features: [
      'Contracts',
      'Reflection',
      'std::execution',
      'Hazard pointers',
      'RCU',
      'Pack indexing',
      'Text encoding',
    ],
  },
}

export const SUPPORTED_VERSIONS: CppVersionId[] = [
  'cpp11',
  'cpp14',
  'cpp17',
  'cpp20',
  'cpp23',
  'cpp26',
]
